### ISSUE TITLE
Web viewer embed possibility

### ISSUE THREAD

**Issue by craigkeeling** [neurolabusc/MRIcro#1]
Curious if there's any way to export to a web-viewable embed? Or if there's any plans to develop that feature?

**Comment by neuronflow** [comment]
I am interested in the same thing!
@craigkeeling did you find a solution?

**Comment by neurolabusc** [comment]
@craigkeeling and @meowlz this project is specific to XCode and MacOS. You can also try my [MRIcroGL](https://github.com/neurolabusc/MRIcroGL/releases) which provides native applications for Windows, Linux and MacOS. 

@RolandR has a [webGL-based ray caster](https://github.com/RolandR/VolumeRayCasting), with a nice [demo](https://draemm.li/various/volumeRendering/webgl2/). Note that WebGL only handles 2D textures, so you need to convert your 3D volume to a 2D image - RolandR's foo.png is a nice example of this method.
